# Generated by Django 4.0.1 on 2022-01-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=150, verbose_name='Position')),
                ('expect_salary', models.CharField(blank=True, default='Negotiable', max_length=20, null=True, verbose_name='Expect Salary')),
                ('total_of_experience', models.CharField(max_length=20, verbose_name='Total of Experience')),
                ('twitter', models.CharField(blank=True, max_length=120, null=True, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, max_length=120, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=120, null=True, verbose_name='LinkedIn')),
                ('instagram', models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram')),
                ('curriculum', models.FileField(blank=True, help_text='Allowed size is 100MB', null=True, upload_to='candidates/curriculums/%Y-%m-%d/', verbose_name='Curriculum')),
                ('candidate_vision', models.TextField(blank=True, null=True, verbose_name='Candidate Vision')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('high_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.education', verbose_name='Education')),
                ('job_type', models.ManyToManyField(to='job.JobType', verbose_name='Job')),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('location', models.CharField(max_length=250, verbose_name='Location')),
                ('logo_url', models.ImageField(blank=True, help_text='Allowed size is 10MB', null=True, upload_to='candidates/experiences/%Y-%m-%d/', verbose_name='Logo')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('start_work', models.DateField(default=django.utils.timezone.now, verbose_name='Start Work')),
                ('end_work', models.DateField(default=django.utils.timezone.now, verbose_name='End Work')),
                ('responsibilities', models.CharField(max_length=250, verbose_name='Responsibility')),
                ('skill_used', models.CharField(max_length=250, verbose_name='Skill Used')),
                ('description', models.TextField(verbose_name='Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('photo_url', models.ImageField(blank=True, help_text='Allowed size is 100MB', null=True, upload_to='candidates/portfolios/%Y-%m-%d/', verbose_name='Photo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('responsibilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.experience', verbose_name='Experience')),
            ],
            options={
                'verbose_name_plural': 'Responsibilities',
            },
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Allowed size is 100MB', null=True, upload_to='portfolios/galleries/%Y-%m-%d/', verbose_name='ThumbNail')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name_plural': 'PortfolioGalleries',
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('PR', 'Poor'), ('FR', 'Fair'), ('GD', 'Good'), ('EL', 'Excellent'), ('MT', 'Mother Tongue')], default='Good', max_length=5, verbose_name='Level')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='Job')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.language', verbose_name='Language')),
            ],
            options={
                'verbose_name_plural': 'LanguageLevels',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=150, verbose_name='School Name')),
                ('major', models.CharField(max_length=150, verbose_name='Major')),
                ('start_year', models.DateField(default=django.utils.timezone.now, verbose_name='Start Year')),
                ('end_year', models.DateField(default=django.utils.timezone.now, verbose_name='End Year')),
                ('logo_url', models.ImageField(blank=True, help_text='Allowed size is 10MB', null=True, upload_to='candidates/educations/%Y-%m-%d/', verbose_name='Logo')),
                ('activities_societies', models.CharField(max_length=250, verbose_name='Activity Society')),
                ('description', models.TextField(verbose_name='Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate', verbose_name='Candidate')),
            ],
            options={
                'verbose_name_plural': 'EducationLevels',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(to='candidate.Skill', verbose_name='Skill'),
        ),
    ]
