# Generated by Django 4.0.1 on 2022-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_benefit',
            field=models.TextField(blank=True, null=True, verbose_name='Benefit'),
        ),
    ]
